# Generated by Django 3.0.8 on 2020-08-04 15:55

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200801_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='UZS', max_digits=12, verbose_name='Price of a product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_fabricator',
            field=models.CharField(blank=True, max_length=127, verbose_name='Fabricator of a product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=127, unique=True, verbose_name='Slug (If no slug, title will be slugified)'),
        ),
    ]
